application: qod-api
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: main.api

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: '2.5.2'

- name: pycrypto
  version: '2.6'

- name: endpoints
  version: 1.0

builtins:
- remote_api: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env$ #virtual environment's folder
